version: '3.9'

services:
  app:
    image: app
    container_name: app
    build:
        context: .
        dockerfile:  docker/Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    ports:
    - "9000:9000"
    volumes:
        - ./:/var/www
    depends_on:
        - db
        - redis
    networks:
        - teach-smith-api

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - teach-smith-api

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:  
      - pgdata:/var/lib/postgresql/data
    networks:
      - teach-smith-api

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - teach-smith-api

  queue:
    image: app
    container_name: queue
    working_dir: /var/www
    volumes:
        - ./:/var/www
    networks:
        - teach-smith-api
    command: php artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
    restart: always
    depends_on:
        - app
  
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" # UI Web
    networks:
      - teach-smith-api

volumes:
  pgdata:

networks:
  teach-smith-api:
    driver: bridge
